### ISSUE TITLE
Vega-Interpreter/Angular 9: CSP unsafe-eval still needs to be activated

### ISSUE THREAD

**Issue by jornfranke** [vega/vega#2694]
Hallo,

I am trying to use Vega-Interpreter in Angular 9 together with vega embed. In my CSP I do not allow unsafe-eval.

I have all my Vega logic in one service. Here is the relevant code snippet:
```
[..]

import * as vegainterpret from 'vega-interpreter';
import embed, {Mode,VisualizationSpec} from 'vega-embed';
import { Renderers } from 'vega';
 [..]

    embedOpts.config={};
            embedOpts.config.ast=true;
       await embed(element, spec, embedOpts);
        
```

Chrome throws the following error related to the CSP:
```
ncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'".
    at Function (<anonymous>)
    at field.js:10
    at Module../node_modules/vega-tooltip/node_modules/vega-util/src/accessors.js (accessors.js:6)
    at __webpack_require__ (bootstrap:79)
    at Module../node_modules/vega-tooltip/node_modules/vega-util/index.js (index.js:1)
    at __webpack_require__ (bootstrap:79)
    at Module../node_modules/vega-tooltip/build/src/formatValue.js (formatValue.js:1)
    at __webpack_require__ (bootstrap:79)
    at Module../node_modules/vega-tooltip/build/src/Handler.js (Handler.js:1)
    at __webpack_require__ (bootstrap:79)
 ```
I am not sure if further parts of Vega are affected as Chrome probably shows only the first issue and not the subsequent ones.

This means I cannot activate CSP for the whole application. 

Did I apply the vega-interpreter wrongly? If not, how should I apply it?
If yes, does the vega-interpreter only apply with embed, but not during general loading of the Vega modules?

Thank you a lot.

**Comment by jheer** [comment]
Looks like the issue is coming out of vega-util (which used to use the Function constructor, but no longer does in recent versions). So first check that all Vega packages are up to date. If that is not the issue, next check that the interpreter is being passed in as an option to the View constructor. I haven’t tested with Vega-embed, so it may be possible the interpreter option is not properly passed when calling `new View`?

**Comment by jornfranke** [comment]
Thanks a lot for the quick answer. The above the source code how I pass it to the source code using vega-embed. It is not clear to me how to pass it for vega-embed.
I use the following versions:
vega-interpreter 1.0.0
vega 5.13.0
vega-embed 6.8.0
vega-lite: 4.13.1

They seem to be the newest version (I checked with npm update).

The error appears already when opening the web application without even going to the page containing Vega (it is a single page Angular application). I assume some vega packages initialize themselves when including them and they still use eval-unsafe.

Otherwise the vega-interpreter is an excellent initiative and thank you for this.

**Comment by domoritz** [comment]
Vega-Embed does not yet pass the ast option to the parser. I can fix it in a few days or you can send a pull request. 

I filed an issue with pointers to relevant code at https://github.com/vega/vega-embed/issues/467.

**Comment by jornfranke** [comment]
Great thanks. I am not so familiar with the Vega internals, so if you can add it in the coming days that would be probably better from a security perspective (i am happily to test it though once pushed to NPM).
I am though not so sure this solves is. As I said, my application does not even reach the codeline where the embed is called. It happens already during initialisation of the vega libraries (simple imports in Angular/Typescript). This means when importing one of the vega packages, there is already an unsafe eval called * as far as I understood*.

**Comment by jornfranke** [comment]
i tried to fix the line in said code. However, i still get the same error. It seems field.js/accessor uses the unsafe Function

**Comment by jornfranke** [comment]
I need it also for Vega and Vega-lite..

**Comment by jornfranke** [comment]
I was probably wrong, it seems to be related only to the embed code line that you stated. I will test the patch once out.

thank you again.

**Comment by domoritz** [comment]
Done in https://github.com/vega/vega-embed/pull/468.

**Comment by domoritz** [comment]
I can reproduce the issue with just Vega. See https://bl.ocks.org/domoritz/7d3b8ed06c079608491a6d4a185f7fd1

**Comment by jheer** [comment]
Thank you @jornfranke  for the issue and @domoritz for the reproduction @domoritz! I plan to investigate and fix within the coming week.

**Comment by jheer** [comment]
Looks like the following code block in the reproduction is wrong:

```js
function render(spec) {
  view = new vega.View(vega.parse(spec), {
    container: "#vis",
    ast: true
  });
  return view.runAsync();
}
```

First, the `ast` option should be passed to the parse method, not the View constructor. Second, the View constructor **must** also be passed the interpreter as an input option. @domoritz, can you update your block to try the following instead? (For more details, read the [Vega interpreter documentation](https://vega.github.io/vega/usage/interpreter/)).

```js
function render(spec) {
  const runtime = view.parse(spec, null, { ast: true });
  view = new vega.View(runtime, {
    expr: vega.expressionInterpreter,
    container: "#vis"
  });
  return view.runAsync();
}
```

**Comment by domoritz** [comment]
Ahh, sorry about that. I didn't look at the code carefully. I updated the block. The changes I made in Vega-Embed look correct to me, though: https://github.com/vega/vega-embed/commit/b0b0c2010a8cd35375daeebfe1bb843c3f2005ee.

**Comment by jheer** [comment]
I just released vega-interpreter 1.0.1 to fix this issue, which stemmed from a build script error. The problem was that the interpreter module and Vega were both trying to set the global `vega` property, rather than extending it. I added the `--extend` CLI argument to the interpreter's rollup call. Now CSP-compliant examples are working for me!

The order of script tags is important! You *must* import vega first, _then_ import vega-interpreter.

**Comment by jornfranke** [comment]
thanks for the quick feedback.
I did not manage yet to get it work with vega-embed, 
vega I still have to test

**Comment by jornfranke** [comment]
I tested that both vega and vega-embed work.
Thank you.
However, I still did not manage to run it under Angular9/Typescript based on a build system. Any ideas hints? The order of imports is correct. I could only imagine somehow that due to optimisations or whatever the Vega module is loaded before. I try to reproduce it on Stackblitz and come back

**Comment by jornfranke** [comment]
Stackblitz requires unsafe-eval itself, so I cannot use it to reproduce it.

I still have the issue with Angular (and I guess for other systems it will be the same). I cannot ensure that vega-interpreter is loaded after vega. Thus, I get always a CSP error.

**Comment by jornfranke** [comment]
Solved also for Angular and other frameworks, see how to use the vega-interpreter in this context here:
https://github.com/vega/vega-embed/issues/473
