### ISSUE TITLE
Tests fail under Node version 7

### ISSUE THREAD

**Issue by kanitw** [vega/vega#664]
(Both @domoritz and I got the same problem)

Note that despite this error, we can still serve local web server or link it to vega editor seamlessly. 

```
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE
npm ERR! vega@3.0.0-beta.5 test: `TZ=America/Los_Angeles tape 'test/**/*-test.js' && eslint index.js src test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vega@3.0.0-beta.5 test script 'TZ=America/Los_Angeles tape 'test/**/*-test.js' && eslint index.js src test'.
npm ERR! This is most likely a problem with the vega package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     TZ=America/Los_Angeles tape 'test/**/*-test.js' && eslint index.js src test
npm ERR! You can get their info via:
npm ERR!     npm owner ls vega
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kanitw/Documents/_code/_idl/_visrec/vega3/npm-debug.log

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE
npm ERR! vega@3.0.0-beta.5 build: `npm run test && uglifyjs build/vega.js -c -m -o build/vega.min.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vega@3.0.0-beta.5 build script 'npm run test && uglifyjs build/vega.js -c -m -o build/vega.min.js'.
npm ERR! This is most likely a problem with the vega package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run test && uglifyjs build/vega.js -c -m -o build/vega.min.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls vega
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kanitw/Documents/_code/_idl/_visrec/vega3/npm-debug.log

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE
npm ERR! vega@3.0.0-beta.5 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vega@3.0.0-beta.5 prepublish script 'npm run build'.
npm ERR! This is most likely a problem with the vega package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls vega
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kanitw/Documents/_code/_idl/_visrec/vega3/npm-debug.log
```

**Comment by jheer** [comment]
Thanks. Will address with the next beta release. The included error message is not very informative. Let me know if you have any upstream error messages showing where in the test suite or linting this failure arises.

**Comment by kanitw** [comment]
Here is the test output https://gist.github.com/kanitw/ec108b6d9e4ee598ba296eb630acfb91. 

Looks like 4 tests are failing ;)

**Comment by jheer** [comment]
Thanks, will investigate soon. In the past I've had problems with different versions of node and node-canvas leading to different test results across platforms. That should be fixed, but it is possible these new errors are related.

If you haven't already, please try a clean install of Vega and let me know if the problem persists.

**Comment by kanitw** [comment]
I just re-clone and run `npm install`.  Interestingly, now I get 2 tests failing instead:
https://gist.github.com/kanitw/ec108b6d9e4ee598ba296eb630acfb91#file-vega-test-output-2

**Comment by jheer** [comment]
Hmm, still can't replicate on my end (currently testing on MacOS under node v5.12). I will investigate further and see what happens with Travis CI before publishing the next Vega release...

**Comment by domoritz** [comment]
I just reinstalled vega and still see errors.

npm: 3.10.9, node: v7.2.0

Logs: https://paste.ee/p/BVI9B

**Comment by jheer** [comment]
I can reproduce the problem if I switch node v7.2. A couple tests fail because coordinate numbers in some layouts / paths change in the last, least-significant digits. Perhaps this is due to some "optimization" of math routines in later v8 versions? Maybe something else? Not really sure. In addition, under node 7.2 I'm also currently unable to successfully compile node-canvas due to an error compiling contextify.

Given these problems, and the fact that node 7 is not yet "recommended for most users", I've gone ahead and released 3.0.0-beta.6 using the existing test suite, which works fine for node versions 0.12 up to 6.9. We can work on node 7 "compliance" with the next incremental release.

In the meantime, Vega should still work fine modulo the failing tests. If you wish to run the test suite without error, set `GENERATE_SCENES = true` in `test/scene-test.js`, run the test suite once, then reset `GENERATE_SCENES = false`. This will re-generate the stored scenegraph instances used as "ground truth" in the test suite.

**Comment by arvind** [comment]
Fwiw, not able to reproduce any failing test cases with a clean check out and `npm install` of vega/vega using node v6.4.0 and npm 3.10.3.

**Comment by jheer** [comment]
I've isolated the outstanding issues here. The `vega-scenegraph` compilation issue I ran into earlier was actually due to the old version of `jsdom` (not `node-canvas` as I said above). Upgrading jsdom to version 9 (and making some related changes in our test code) solves that problem.

That leaves the problem of getting different layout/path calculations on node 7. After some hunting, it appears all of our test failures stem from a single deviation: the output of `Math.atan2`. For example:
```
// Node 6.9.2
> Math.atan2(2.220446049250313e-16, -0.9999999999999998)
3.1415926535897927

// Node 7.2.0
> Math.atan2(2.220446049250313e-16, -0.9999999999999998)
3.141592653589793

// Google Chrome
> Math.atan2(2.220446049250313e-16, -0.9999999999999998)
3.141592653589793
```

The difference is small enough to leave the visualizations looking identical, but breaks the test cases. I can think of two possible solutions off the top of my head: (1) maintain multiple "ground truth" sets and dynamically select the correct one based on the node version (ugh), (2) introduce slightly modified code that reduces precision so that one set of tests passes for all versions. Both are rather annoying, let me know if you have other ideas...

**Comment by arvind** [comment]
> (2) introduce slightly modified code

I assume this is referring to _test_ code (rather than scenegraph code)? For example, chai has [approximate](http://chaijs.com/api/assert/#method_approximately)/[closeTo](http://chaijs.com/api/bdd/#method_closeto) assertions. If so, as the less onerous of the two strategies to maintain, my vote would be to do that.

**Comment by jheer** [comment]
Test code, absolutely. I would normally just do "closeTo" but that's not so handy for testing SVG path strings, scenegraph JSON, etc. Right now I'm thinking we might monkey patch Math.atan2 directly, then restore after tests complete. Better ideas welcomed!

**Comment by domoritz** [comment]
Monkey patching `Math.atan2` to have lower precision sounds like the best way to go. 

Since jsdom only works for node 4+ but is only required for tests, does this mean we are not going to test on node 0.12 but still say we support it?

**Comment by mr23** [comment]
Reduce the precision,  but only on the test? 
-- 
-Chris

**Comment by jheer** [comment]
As of 0b4221e05670e427f2fb895acc522cabea46cb4a, we're now node 7 compliant, and have dropped explicit support for node 0.12. (Vega, but not the test suite, should still work under 0.12.)

After more investigation, I found problems beyond `Math.atan2`. So I bit the bullet and added a new specialized "deepEquals" operator (with error tolerance for numbers) for Vega scenegraphs and SVG paths. Upon reflection I decided this was the cleaner, more future-proof (and more time-efficient) route. These are exported as the new `sceneEqual` and `pathEqual` utilities in `vega-scenegraph`.
